export default {
  autoSave: false,
  withFrame: true,
  withStretchLine: true,
  withSnow: false,
  withPetals: false,
  withMoon: true,
  withShooringStar: false,
  withMonolith: false,
  withFireworks: false,
  withMilkyway: false,
  pixelated: false,
  mountainShade: true,
  bgColor: [172.5, 164.5, 158],
  fogColor: [255, 255, 255],
  fogStrength: 1,
  pixelRatio: 1,
  maxHeight: 4,
  noiseScale: 1.2,
  planeSize: 20,
  colorTheme: "Blue",
  debug: false,
  moonPosition: 0,
  superMoon: false,
  meterShower: false,
};
